[package]
name = "rm-frust5-api"
version = "0.1.0"
edition = "2021"

[lib]
name = "frust5_api"
path = "src/lib.rs"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
hdf5 = "0.8"